# Generated by Django 4.2.6 on 2023-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_TESS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
