# Generated by Django 4.2.6 on 2023-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_TESS', '0002_extractedtext_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedtext',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
